version: '{build}'

image:
  - Visual Studio 2019 Preview

configuration:
  - Release

build:
  project: kPassKeep.sln
  verbosity: minimal
  
# Retain the NuGet package cache between builds.
cache:
  - C:\Users\appveyor\AppData\Local\NuGet\Cache
  - C:\Users\appveyor\.nuget\packages
  
before_build:
  - nuget restore

after_build: >
  7z a kPassKeep.zip
  "%APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.dll"
  "%APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\kPassKeep.exe.config"
  "%APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\kPassKeep.exe"
artifacts:
  - path: kPassKeep.zip

deploy:
  release: $(appveyor_repo_tag_name)
  provider: GitHub
  auth_token:
    secure: l2f1NUjO28c5EweLBmCLsLt52XiJnXZr5fcKyedrLEkOt3NJ9alnk2PoZLYXxp1H
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
